server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kq?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a123


  redis:
    host: 127.0.0.1
    port: 6379
    #password: a123
    # 连接超时时间（毫秒）
    timeout: 3000

    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）200
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


